pipeline {
    agent any
    tools {
        nodejs 'node-11.10.0'
    }
    stages {
        stage('SCM Checkout') {
            steps {
                git branch: 'development', credentialsId: 'jenk', url: 'git@github.com:LinoHallerRios/AppLecturas.git'
            }
        }
        stage('Install'){
          steps {
            parallel 'Client Install': {
              script {
                sh 'cd client && npm install'
              }
            }, 'Server Install': {
              script {
                sh 'cd server && npm install'
              }
            }
          }
        }
        stage('Build'){
          steps {
            parallel 'Client Build': {
              script {
                sh 'cd client && npm build'
              }
            }, 'Server Build': {
              script {
                sh 'cd server && npm build'
              }
            }
          }
        }
        stage('Sonar Gate') {
          steps{
            script {
              def scannerHome = tool 'Sonarqube Scanner';
              withSonarQubeEnv('sonar-6'){
                  sh "${scannerHome}"
              }
              timeout(time: 30 , unit: 'MINUTES'){
                def qg = waitForQualityGate()
                if (qg.status != 'OK') {
                  error "Pipeline abortado por no pasar quality gates: ${qg.status}"
                }
              }
            }
          }
        }
        stage('IBMCloud Deploy') {
          steps {
            script {
              sh 'echo Realizando deploy en Ibmcloud...'
            }
          }
        }
    }
}
